### ISSUE TITLE
Provide Dart wizards

### ISSUE THREAD

**Issue by vogella** [eclipse/dartboard#41] opened 2019-06-24 08:12 UTC
I suggest to add a new Dart project wizard and a new Dart file wizard. For Eclipse users is it quite normal to have wizards for creating new elements.

**Comment by jonas-jonas** [comment] 2019-06-24 08:22
Duplicate of https://github.com/eclipse/dartboard/issues/6

**Closed by jonas-jonas** 2019-06-24 08:22 UTC

**Comment by vogella** [comment] 2019-06-24 08:31
Fine to handle this via #6 but context menu is not the same as File-> New wizard IMHO.
